project:
  type: website
  output-dir: compiled
  render:
    - "*.qmd"

website:
  title: "Machine Learning"
  sidebar: 
    style: docked
    contents:
      - section: "Lectures"
        contents:
        - lecture-1.qmd
        - lecture-2.qmd
        - lecture-3.qmd
        - lecture-4.qmd
      - section: "Labs"
        contents:
        - lab-1.qmd

format:
  html:
    theme: [yeti, style.scss]
    css: styles.css
    toc: true
  revealjs: 
    theme: [serif, revealjs-style.scss]
    scrollable: true
    smaller: false
    slide-number: true
    slide-level: 2
    navigation-mode: vertical
    transition: slide

