---
title: "Machine Learning"
format:
    html: default
---

Welcome to the Machine Learning course developed for the MIR Masters Engineering and
Complex Systems. In this series of lectures, we're going to learn about how to
learn! Specifically, we're going to learn about how computers learn using Machine
Learning algorithms. We'll learn about the basic understanding of learning
algorithms, as well as specific algorithms that include: linear models, support
vector machines, and clustering methods. In addition to these algorithms, we will
also look at a key part of using any learning algorithm -- evaluating it!

Below you can find the lectures presented in this course, in a HTML or PDF format. If
you have any questions or concerns, you can contact me using my email address `jay.morgan@univ-tln.fr`

## Lectures

- Lecture 1 - [Introduction](lecture-1.qmd)
- Lecture 2 - [Linear Models](lecture-2.qmd)
- Lecture 3 - [Evaluation of Models](lecture-3.qmd)
- Lecture 4 - [Support Vector Machines](lecture-4.qmd)
- Lecture 5 - [K-Nearest Neighbours & K-Means](lecture-5.qmd)

## Labs

- Lab 1 - [Linear Models](lab-1.qmd)
- Lab 2 - [Evaluation of Models](lab-2.qmd)
- Lab 3 - [K-Nearest Neighbours](lab-3.qmd)